name: Packer
on:
  push:
      paths:
        - '*.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate packer-template.json
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: validate packer-template.json
      - name: packer build packer-template.json
        uses: docker://hashicorp/packer:1.4.3
        with:
          args: build packer-template.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1