parameters:
- name: imagesMenu
  displayName: Image Selection
  type: string
  default: win2019_default
  values:
  - 2012R2_base
  - 2012R2_default
  - 2016_base
  - 2016_default
  - 2016_update
  - 2019_base
  - 2019_default
  - ubuntu18_base
- name: osMenu
  displayName: Select OS
  type: string
  default: windows
  values:
  - windows
  - linux
  - vmware
  - all
- name: imageVarFile
  displayName: Select Credentials
  type: string
  default: windows
  values:
  - default
  - production
  - debug
  - all
- name: providerMenu
  displayName: Select Provider
  type: string
  default: aws
  values:
  - aws
  - azure
  - vcenter
  - all



name: 'Packer-AWS'
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: packer validate packer-aws-template.json
        uses: docker://hashicorp/packer:1.7.0
        with:
          args: validate packer-aws-template.json
      - name: packer build packer-aws-template.json
        uses: docker://hashicorp/packer:1.7.0
        with:
          args: build packer-aws-template.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1